### ISSUE TITLE
Notification stop button working on android but not on IOS

### ISSUE THREAD

**Issue by hafidzaini** [gdelataillade/alarm#320]
Hello,
is notifcation tap on IOS to stop alarm still under development?
it working perfectly on Android but not working on IOS

**Comment by gdelataillade** [comment]
What version ?
Are you talking about the stop button in the notification or just tapping the notification ?

**Comment by hafidzaini** [comment]
latest version. 4.1.1

stop button on android working perfectly.
but on ios, notification pop, no stop button showing, when i tap, it open app instead of turn off alarm.
what did i miss 🤔

**Comment by gdelataillade** [comment]
I remember having this issue before but I thought it was fixed. I'll take a look later, in the meantime you can try version `5.0.0-dev.6` [here](https://pub.dev/packages/alarm/versions/5.0.0-dev.6/changelog), which is a test versions for version 5, which should be released soon. I believe you won't have the issue with this version. Let me know how it goes.

**Comment by hafidzaini** [comment]
thank you very much.
will report later 🙏

**Comment by hafidzaini** [comment]
cant update to alarm dev version because of shared_pref version.
still using flutter branch 3.22.3, changin to stable channel 3.27.2 now.
will update again later 🙏

**Comment by hafidzaini** [comment]
flutter stable channel 3.27.2 with alarm 4.1.1, still no luck.
stop button not showing.
changing to alarm dev 5.0.0-dev.6 now.
will update later 🙏

**Comment by gdelataillade** [comment]
What's your error ?

**Comment by hafidzaini** [comment]
no error shown, using flutter 3.27.2 with alarm 4.1.1, stop button on notification not showing up.
so when tapping notification on ios. it just open app, instead of turn of alarm.

now using alarm 5.0.0-dev.6, xcode 16.2, ios 18.2 still not showing.
working fine on android sdk 34.0.0

still dont get the error message yet, will debug later
here is the screenshot

![](https://i.imgur.com/5ajhpHg.png)
![](https://i.imgur.com/ZEtbgNZ.png)

**Comment by hafidzaini** [comment]
my temporary fix to stop alarm when notification pop on IOS is, check Alarm.isRinging() on App lifecycle onResume and stop it  🫣

**Comment by orkun1675** [comment]
IIUC the current behaviour is (a) tap -> opens the app, (b) tap and hold to reveal actions -> tap stop button -> dismisses alarm and opens app.

Does (b) work for you?

Maybe we can improve this UX by making regular taps reveal the actions buttons.

**Comment by gdelataillade** [comment]
@Ketan-Satani-Innovuratech your stop button is just not showing ?
Have you configured it in `AlarmSettings.notificationSettings.stopButton` ?

Note that, as mentioned in the documentation, it won't work for iOS if the app was previously killed and not reopened.

**Comment by Ketan-Satani-Innovuratech** [comment]
@Gdelataillade Also, my app was not killed or reopened. The app is in the foreground only, and I am testing it. Please let me know why the STOP button did not appear?

**Comment by gdelataillade** [comment]
Please show some code. It is difficult to know what's wrong without more information.

Also, just to be sure, have you followed the [iOS installation steps](https://github.com/gdelataillade/alarm/blob/main/help/INSTALL-IOS.md) ?

**Comment by gdelataillade** [comment]
In the code you provided, you only schedule the alarm with the condition `Platform.isAndroid`.
